### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by thesuox** [sibstu-ivt/main#1]
Привет, это Стас Кащеев (новенький). Можешь скинуть пример дневника своего, как его нужно правильно заполнять. Там, я так понимаю, всего три страницы нужно заполнить? Можешь кинуть фотку сюда или на ленту принести?

**Comment by NumminorihSF** [comment]
я дневник не заполнял еще, практику буду на выходных оформлять

**Comment by thesuox** [comment]
Костя, а ты можешь взять с собой лекции и другие материалы по методам оптимизации на завтрашние лекции. Я бы их скопировал. А то у меня вообще нихера нет.

**Comment by NumminorihSF** [comment]
добавил в репозиторий папку _current_session, в ней есть архив по методам оптимизации. пароль тот же, что и на лекциях по бд

**Comment by thesuox** [comment]
Про пароль ничего не знаю намекни

**Comment by NumminorihSF** [comment]
Пароль от архива - номер группы из расписания (все, что до "_3к" идет, включая точки).

**Comment by NumminorihSF** [comment]
Так, завтра занятий не будет. Подробности в понедельник

**Comment by thesuox** [comment]
В субботу ты имеешь ввиду? А почему?
